import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import Header from "@/components/Header"
import Footer from "@/components/Footer"
import './globals.css'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Coffee Marketplace App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-y-scroll scrollbar-thin scrollbar-thumb-coffee scrollbar-track-cream` }
      >
        <Header/>
        <main className="bg-[#e0c9af]">{children}</main>
        <Footer/>
      </body>
    </html>
  )
}
