# Generated by Django 5.2.5 on 2025-08-27 13:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cart_item',
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_quantity',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999)]),
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
